#!/usr/bin/python

import csv

# Generates go/ts baes stats files from assets/db_inputs/basestats

BASE_DIR = ""

DIR_PATH = "assets/db_inputs/basestats/"
OUTPUT_PATH = "sim/core/"

BASE_MP = "octbasempbyclass.txt"
MELEE_CRIT = "chancetomeleecrit.txt"
MELEE_CRIT_BASE = "chancetomeleecritbase.txt"
SPELL_CRIT = "chancetospellcrit.txt"
SPELL_CRIT_BASE = "chancetospellcritbase.txt"
RATING_SCALAR = "octclasscombatratingscalar.txt"

BASE_LEVEL = 70

Offs = {
    "Warrior": 0,
    "Paladin": 1,
    "Hunter": 2,
    "Rogue": 3,
    "Priest": 4,
    "Shaman": 6,
    "Mage": 7,
    "Warlock": 8,
    "Druid": 10,
}

#Warrior	Paladin	Hunter	Rogue	Priest	Shaman	Mage	Warlock	Druid
def GenIndexedDb(file : str):
    db = {}
    with open(file) as tsv:
        first = True
        for line in csv.reader(tsv, delimiter="\t"):
            if first:
                first = False
                continue
            db[line[0]] = line[1:]
    return db

class ClassStats:
    BaseMp : dict
    MCrit : dict
    SCrit : dict
    MCritBase : dict
    SCritBase : dict

def GenExtraStatsGoFile(cs: ClassStats):
    header = '''
package core

// **************************************
// AUTO GENERATED BY BASE_STATS_PARSER.PY
// **************************************

import (
    "github.com/wowsims/tbc/sim/core/proto"
    "github.com/wowsims/tbc/sim/core/stats"
)

'''
    output = header
    # Combat-rating conversions are ruleset data. Keeping them out of this
    # generated file prevents a base-stat refresh from silently changing the
    # inherited profile or recreating its public compatibility constants.

    output += '''var CritPerAgiMaxLevel = map[proto.Class]float64{
proto.Class_ClassUnknown: 0.0,'''
    for c in ["Warrior", "Paladin", "Hunter", "Rogue", "Priest", "Shaman", "Mage", "Warlock", "Druid"]:
        cName = c.split()
        cName = ''.join(cName)
        mc = float(cs.MCrit[str(BASE_LEVEL)][Offs[c]])*100
        output += f"\nproto.Class_Class{cName}: {mc:.8f},"
    output += "\n}\n"

    output += '''var CritPerIntMaxLevel = map[proto.Class]float64{
proto.Class_ClassUnknown: 0.0,'''
    for c in ["Warrior", "Paladin", "Hunter", "Rogue", "Priest", "Shaman", "Mage", "Warlock", "Druid"]:
        cName = c.split()
        cName = ''.join(cName)
        mc = float(cs.SCrit[str(BASE_LEVEL)][Offs[c]])*100
        output += f"\nproto.Class_Class{cName}: {mc:.8f},"
    output += "\n}\n"

    output += '''var ExtraClassBaseStats = map[proto.Class]stats.Stats{
proto.Class_ClassUnknown: {},'''
    for c in ["Warrior", "Paladin", "Hunter", "Rogue", "Priest", "Shaman", "Mage", "Warlock", "Druid"]:
        cName = c.split()
        cName = ''.join(cName)
        output += f"\nproto.Class_Class{cName}: {{"
        mp = float(cs.BaseMp[str(BASE_LEVEL)][Offs[c]])
        scb = float(cs.SCritBase["1"][Offs[c]])*100
        mcb = float(cs.MCritBase["1"][Offs[c]])*100
        output += f"\n stats.Mana: {mp:.4f},"
        output += f"\n stats.SpellCritPercent: {scb:.4f},"
        output += f"\n stats.PhysicalCritPercent: {mcb:.4f},"
        output += "\n},"
    output += "\n}\n"
    return output


if __name__ == "__main__":
    args = ClassStats()
    args.BaseMp = GenIndexedDb(BASE_DIR + DIR_PATH + BASE_MP)
    args.MCrit = GenIndexedDb(BASE_DIR + DIR_PATH + MELEE_CRIT)
    args.SCrit = GenIndexedDb(BASE_DIR + DIR_PATH + SPELL_CRIT)
    args.MCritBase = GenIndexedDb(BASE_DIR + DIR_PATH + MELEE_CRIT_BASE)
    args.SCritBase = GenIndexedDb(BASE_DIR + DIR_PATH + SPELL_CRIT_BASE)

    output = GenExtraStatsGoFile(args)
    fname = BASE_DIR + OUTPUT_PATH + "base_stats_auto_gen.go"
    print(f"Writing stats to: {fname}")
    f = open(fname, "w")
    f.write(output)
    f.close()
